package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

import com.example.jdbcdemo.domain.Producent;
import com.example.jdbcdemo.domain.Produkt;

public class ProducentManager {
	private Connection connection;
	private Statement statement;
	
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	
	private String createTableProducent = 
			"CREATE TABLE Producent(" +
					"id int GENERATED BY DEFAULT AS IDENTITY, " +
					"nazwa varchar(20), " +
					"miasto varchar(15), " +
					"nrTel varchar(15), " +
					"nip int, " +
					"PRIMARY KEY (id))";
	
	private String createTableProdukt = 
			"CREATE TABLE Produkt(" +
					"id int GENERATED BY DEFAULT AS IDENTITY, " +
					"nazwa varchar(30), " +
					"cena DOUBLE, " +
					"znizka DOUBLE, " +
					"producentId int, " +
					"PRIMARY KEY (id), " +
					"FOREIGN KEY (producentId) REFERENCES Producent(id))";
	
	}